### ISSUE TITLE
点击Button组件loading场景下，按钮仍然可以触发事件的问题

### ISSUE THREAD

**Issue by overcastsky** [PIdoll/DBox#432]
步骤：
我在点击按钮以后，像后端请求数据，且在这过程中，我需要将按钮添加loading效果，并且需要后台返回结果以后，才将按钮loading效果去除，以防止用户多次重复点击。

期望：
希望得到的效果是，后台在未返回数据之前，按钮处于loading状态，且点击不会触发任何事件

得到的：
上述的效果并未实现，Button在loading状态下点击仍然可以触发

环境：
react16.5

**Comment by cxm1011** [comment]
已解决  将下一版本修复
